version: '3.8'
services:
  wordpress:
    container_name: 'my-wp-plugin-app'
    image: 'wordpress:latest'
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_NAME: my_wp_plugin_db
      WORDPRESS_DB_USER: my_wp_plugin_user
      WORDPRESS_DB_PASSWORD: my_wp_plugin_password
    volumes:
      - './wordpress:/var/www/html'
      - type: bind
        source: './my-wp-plugin'
        target: '/var/www/html/wp-content/plugins/my-wp-plugin'
  db:
    container_name: 'my-wp-plugin-db'
    image: 'mysql:5.7'
    volumes:
      - './data/mysql:/var/lib/mysql'
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: my_wp_plugin_db
      MYSQL_USER: my_wp_plugin_user
      MYSQL_PASSWORD: my_wp_plugin_password
